export const pilots = [
  {
    id: 0,
    name: "The Wright Brothers",
    fullName: "Orville & Wilbur Wright",
    years: "1867 & 1871",
    nationality: "🇺🇸 American",
    era: "✈️ Invented Flying",
    image: "/images/wright_portrait.jpg",
    planeImage: "/images/wright_plane.jpg",
    planeCaption: "The Wright Flyer — the very first airplane! (1903)",
    tagline: "They built the very first airplane!",
    color: "#0a2a4a",
    accentColor: "#4fc3f7",
    achievement: "🏆 First airplane flight EVER!",
    achievementDetail: "December 17, 1903 in Kitty Hawk, USA",
    bio: "Orville and Wilbur Wright were two brothers who fixed bicycles for a living. But they had a BIG dream — they wanted to fly! They worked very hard, did lots of experiments, and built the world's very first airplane. On December 17, 1903, they made history!",
    facts: [
      "✈️ Their first flight was only 12 seconds long!",
      "📏 The plane flew just 120 feet — shorter than a school bus!",
      "🔁 They flew 4 times in one day",
      "🔧 They built their own airplane in their bicycle shop",
      "📚 Neither brother went to college — they were self-taught!"
    ],
    funFact: "🤩 Fun Fact: Their first flight was so short, it could fit inside a modern airplane!",
    quote: "If birds can fly, then why can't I?",
    quoteAuthor: "— Orville Wright",
    badge: "🥇 First in Flight"
  },
  {
    id: 1,
    name: "Charles Lindbergh",
    fullName: "Charles Lindbergh",
    years: "1902",
    nationality: "🇺🇸 American",
    era: "🌊 Golden Age of Flying",
    image: "/images/lindbergh_portrait.jpg",
    planeImage: "/images/lindbergh_plane.jpg",
    planeCaption: "The Spirit of St. Louis — flew across the Atlantic Ocean!",
    tagline: "He flew alone across a whole ocean!",
    color: "#0d2b0d",
    accentColor: "#69f0ae",
    achievement: "🏆 First solo flight across the Atlantic Ocean!",
    achievementDetail: "May 20–21, 1927 — New York to Paris",
    bio: "Imagine flying alone over a huge ocean for more than 33 hours — with NO sleep! That is exactly what Charles Lindbergh did. He flew from New York all the way to Paris, France. Nobody had ever done it alone before. The whole world went wild with excitement!",
    facts: [
      "🌊 He flew over 5,800 km — all alone!",
      "😴 He stayed awake for over 33 hours straight",
      "🔭 His plane had no front window — he used a periscope!",
      "🎉 100,000 people came to cheer when he landed in Paris",
      "👦 He was only 25 years old — very young!"
    ],
    funFact: "🤩 Fun Fact: He brought only 5 sandwiches for the whole trip across the ocean!",
    quote: "What a dream — to fly alone across the great Atlantic Ocean!",
    quoteAuthor: "— Charles Lindbergh",
    badge: "🌊 Ocean Crosser"
  },
  {
    id: 2,
    name: "Amelia Earhart",
    fullName: "Amelia Earhart",
    years: "1897",
    nationality: "🇺🇸 American",
    era: "💪 Breaking Barriers",
    image: "/images/earhart_portrait.jpg",
    planeImage: "/images/earhart_plane.jpg",
    planeCaption: "Amelia with her Lockheed Electra airplane",
    tagline: "The bravest woman in the sky!",
    color: "#3a0d36",
    accentColor: "#f48fb1",
    achievement: "🏆 First woman to fly solo across the Atlantic!",
    achievementDetail: "May 1932 — from Canada to Ireland",
    bio: "Amelia Earhart was super brave! When she was a little girl, people said girls could not fly planes. But Amelia did not listen. She learned to fly, broke lots of records, and showed the whole world that ANYONE can follow their dreams. She is a hero for everyone!",
    facts: [
      "🌟 She was the first woman to fly alone across the Atlantic Ocean",
      "✈️ She got her pilot's license when she was just 24",
      "👩‍✈️ She helped start a club just for women pilots",
      "🏅 She won a special medal called the Distinguished Flying Cross",
      "🔍 She disappeared in 1937 — it is still a mystery today!"
    ],
    funFact: "🤩 Fun Fact: She saw her first airplane at a fair but didn't think much of it. She changed her mind later!",
    quote: "The most difficult thing is deciding to act. The rest is just not giving up!",
    quoteAuthor: "— Amelia Earhart",
    badge: "👩‍✈️ Sky Trailblazer"
  },
  {
    id: 3,
    name: "Chuck Yeager",
    fullName: "Chuck Yeager",
    years: "1923",
    nationality: "🇺🇸 American",
    era: "💨 Jet Age",
    image: "/images/yeager_portrait.jpg",
    planeImage: "/images/yeager_plane.jpg",
    planeCaption: "The Bell X-1 rocket plane — faster than sound!",
    tagline: "He flew FASTER than sound!",
    color: "#2d1000",
    accentColor: "#ffb74d",
    achievement: "🏆 First person to fly faster than the speed of sound!",
    achievementDetail: "October 14, 1947 — in the Bell X-1 rocket plane",
    bio: "Did you know that sound travels super fast — about 1,235 km per hour? Chuck Yeager flew even FASTER than that! He flew a special rocket plane called the Bell X-1. The coolest part? He had two broken ribs that day but still did it! He was incredibly brave.",
    facts: [
      "💨 He flew at 1,299 km/h — faster than the speed of sound!",
      "🤕 He had TWO broken ribs but still flew that day!",
      "✈️ He was a great fighter pilot in World War 2",
      "🎯 He once shot down 5 enemy planes in just one flight!",
      "👴 He kept flying jet planes even when he was 70 years old"
    ],
    funFact: "🤩 Fun Fact: When a plane goes faster than sound, it makes a giant BOOM noise called a sonic boom!",
    quote: "Don't think about the risks. Think about the results!",
    quoteAuthor: "— Chuck Yeager",
    badge: "💨 Sound Breaker"
  },
  {
    id: 4,
    name: "The Red Baron",
    fullName: "Manfred von Richthofen",
    years: "1892",
    nationality: "🇩🇪 German",
    era: "⚔️ World War 1",
    image: "/images/richthofen_portrait.jpg",
    planeImage: "/images/richthofen_plane.jpg",
    planeCaption: "The red Fokker triplane — the most famous WWI fighter!",
    tagline: "The most famous fighter pilot ever!",
    color: "#2a0000",
    accentColor: "#ef5350",
    achievement: "🏆 Won 80 air battles — the most of anyone in World War 1!",
    achievementDetail: "During World War 1, 1916–1918",
    bio: "Manfred von Richthofen was a German pilot in World War 1. He was so good at flying and fighting that pilots on BOTH sides were scared of him! He painted his plane bright red so everyone could see him coming. That is why people called him the RED BARON. He became one of the most famous pilots in all of history.",
    facts: [
      "🔴 He painted his airplane bright RED so everyone knew it was him",
      "🏆 He won 80 air battles — nobody in WW1 won more!",
      "🎪 His group of planes was called the 'Flying Circus'",
      "🫡 Even enemy soldiers respected him deeply",
      "🎂 He was only 25 years old when he died as a hero"
    ],
    funFact: "🤩 Fun Fact: His bright red plane made him so famous that Snoopy from Peanuts pretends to fight the Red Baron!",
    quote: "Everything depends on being bold!",
    quoteAuthor: "— The Red Baron",
    badge: "🔴 The Red Baron"
  },
  {
    id: 5,
    name: "Neil Armstrong",
    fullName: "Neil Armstrong",
    years: "1930",
    nationality: "🇺🇸 American",
    era: "🚀 Space Age",
    image: "/images/armstrong_portrait.jpg",
    planeImage: "/images/armstrong_plane.jpg",
    planeCaption: "Neil Armstrong walking on the Moon — July 20, 1969! 🌙",
    tagline: "He flew all the way to the MOON! 🌙",
    color: "#040d1e",
    accentColor: "#90caf9",
    achievement: "🏆 First human being to walk on the Moon!",
    achievementDetail: "July 20, 1969 — Apollo 11 Mission",
    bio: "Neil Armstrong was a pilot, a soldier, and an astronaut. But his most amazing moment was on July 20, 1969. He flew a rocket to the Moon and became the FIRST human in all of history to walk on it! 600 million people watched on TV. That is more than all the people in the USA and Europe COMBINED!",
    facts: [
      "🌙 He was the FIRST human to ever walk on the Moon",
      "📺 600 million people watched on TV — that's a lot of people!",
      "✈️ He flew 78 war missions before becoming an astronaut",
      "🛸 The Moon is 384,000 km away from Earth",
      "🙏 He was very quiet and humble about his amazing achievement"
    ],
    funFact: "🤩 Fun Fact: His footprints are STILL on the Moon right now — because there is no wind to blow them away!",
    quote: "That's one small step for man — one giant leap for mankind!",
    quoteAuthor: "— Neil Armstrong, on the Moon, 1969",
    badge: "🌙 Moon Walker"
  },
  {
    id: 6,
    name: "Captain Sully",
    fullName: "Chesley 'Sully' Sullenberger",
    years: "1951",
    nationality: "🇺🇸 American",
    era: "🦅 Modern Hero",
    image: "/images/sully_portrait.jpg",
    planeImage: "/images/sully_plane.jpg",
    planeCaption: "Flight 1549 on the Hudson River — everyone survived! 🙌",
    tagline: "He saved 155 people in 3 minutes!",
    color: "#001d2e",
    accentColor: "#4dd0e1",
    achievement: "🏆 Saved 155 lives by landing on the Hudson River!",
    achievementDetail: "January 15, 2009 — New York City",
    bio: "On January 15, 2009, Captain Sully's airplane hit a flock of birds right after taking off. Both engines stopped working! Sully had only 3 minutes to save everyone. He stayed very calm, thought very fast, and landed the plane on the Hudson River. ALL 155 people survived. People called it the Miracle on the Hudson!",
    facts: [
      "🦅 Both engines stopped after hitting birds in the sky",
      "⏱️ He had less than 3 minutes to save everyone!",
      "💧 He landed the plane on a RIVER like a boat",
      "🙌 ALL 155 passengers were saved — not one person was lost",
      "🎖️ He had 40 years of flying experience — it really helped!"
    ],
    funFact: "🤩 Fun Fact: A movie called 'Sully' was made about this hero. Maybe you can watch it with your family!",
    quote: "I have been flying for 42 years. When the moment came, I was ready.",
    quoteAuthor: "— Captain Sully",
    badge: "🦅 The Hudson Hero"
  }
];
